name: Actions Workflow
on:
  repository_dispatch:
    types: [dinesh_build]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo "${{github.event.client_payload.env}}"
          echo "${{github.event.client_payload.artifact}}"
      - name: List Files
        run: |
          pwd
          ls -altr
                
          mkdir dinesh
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Dinesh
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}"