name: Cron Job 5mins Job
on: 
  repository_dispatch:
  #schedule:
  # - cron: '*/5 * * * *'
  pull_request:
    types: [dinesh_build]
jobs:
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run:
          pwd
          ls -altr
         
    
          