name: Trigger WF through Postman
on: 
  repository_dispatch:
  #schedule:
  # - cron: '*/5 * * * *'
  pull_request:
    types: [dinesh_build]
    steps:
      - name: payload
        run: echo ${{github.event.client_payload.env}}

jobs:
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run:
          pwd
          ls -altr
         
    
          