name: Cron Job Testing Workflow
on: 
  push:
  issues:
    types: open
  schedule:
    - cron: '* * * * *'
  

jobs:
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run:
          pwd
          ls -altr
         
    
          